# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tr_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translater', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=4000)),
                ('passage_title', models.CharField(default='none', max_length=50)),
                ('be_translated', models.BooleanField(default=False)),
                ('ordinary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr_user.Ordinary_User')),
            ],
            options={
                'db_table': 'passages',
            },
            managers=[
                ('passages', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(default=' ', max_length=4000)),
                ('result', models.TextField(max_length=4000)),
                ('if_was_chosen', models.BooleanField(default=False)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr_passage.Passage')),
                ('translater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr_user.Translater')),
            ],
            options={
                'db_table': 'passageResults',
            },
            managers=[
                ('results', django.db.models.manager.Manager()),
            ],
        ),
    ]
