# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinary_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_passWord', models.CharField(max_length=40)),
                ('account_mail', models.CharField(max_length=30)),
                ('choose_translater', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'ordinaryUser',
                'ordering': ['id'],
            },
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Translater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_passWord', models.CharField(max_length=40)),
                ('account_mail', models.CharField(max_length=30)),
                ('credit_level', models.IntegerField(null=True)),
                ('score_sum', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'translater',
                'ordering': ['id'],
            },
            managers=[
                ('translaters', django.db.models.manager.Manager()),
            ],
        ),
    ]
