# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_user', '0002_auto_20171226_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinary_user',
            name='account_mail',
            field=models.CharField(default='123@qq.com', max_length=30),
        ),
    ]
